version: "3.4"

services:
  frontend:
    container_name: frontend
    build: ./components/frontend
    networks:
      default:
        aliases:
          - "compose-p2p-frontend"

  backend:
    container_name: backend
    volumes:
      - "./sqllite/:/sqllite-db/"
    build: ./components/backend
    ports:
      - "5000:5000"
    networks:
      default:
        aliases:
          - "compose-p2p-backend"

  jupyter:
    container_name: jupyter
    volumes:
      - "./components/jupyter/notebooks/:/home/jovyan/work/"
    build: ./components/jupyter
    ports:
      - "8888:8888"

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    networks:
      default:
        aliases:
          - "compose-postgres"

  proxy:
    container_name: proxy
    build: ./components/proxy
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - "compose-proxy"
    restart: always

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2019-01-16T21-44-08Z
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    networks:
      default:
        aliases:
          - "compose-minio"

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    volumes:
      - "./components/backend/swagger.yml:/swagger.yml:ro"
    environment:
      SWAGGER_JSON: /swagger.yml
    networks:
      default:
        aliases:
          - "compose-swagger-ui"
