swagger: "2.0"
info:
  version: "0.1.0"
  title: "Pandas to Production"

host: "localhost"

basePath: "/api"

schemes:
  - "http"

paths:
  /sites/{siteId}/pages/:
    get:
      tags:
        - "pages"
      operationId: "listPagesBySite"
      parameters:
        - name: "siteId"
          in: "path"
          description: "Site ID"
          required: true
          type: "string"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Page"

  /sites/{siteId}/pages/{pageId}:
    get:
      tags:
        - "pages"
      operationId: "getPage"
      parameters:
        - name: "siteId"
          in: "path"
          description: "Site ID"
          required: true
          type: "string"
        - name: "pageId"
          in: "path"
          description: "Page ID"
          required: true
          type: "string"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Page"

  /sites/:
    get:
      tags:
        - "sites"
      operationId: "listSites"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Site"

  /sites/{siteId}:
    get:
      tags:
        - "sites"
      operationId: "getSite"
      parameters:
        - name: "siteId"
          in: "path"
          description: "Site ID"
          required: true
          type: "string"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Site"

  /dataframes/{dataframeId}:
    get:
      tags:
        - "dataframes"
      operationId: "getDataframe"
      parameters:
        - name: "dataframeId"
          in: "path"
          description: "Dataframe ID"
          required: true
          type: "string"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Dataframe"

definitions:
  Page:
    type: "object"
    properties:
      id:
        type: "string"
      title:
        type: "string"
        example: "Weekly Report"
      content:
        type: "object" # TBD
      site_id:
        type: "string"

  Site:
    type: "object"
    properties:
      id:
        type: "string"
      slug:
        type: "string"
        example: "client-abc-weekly-report"
      default_page_id:
        type: "string"

  Dataframe:
    type: "object"
    properties:
      id:
        type: "string"
      digest:
        type: "string"
      url:
        type: "string"
