swagger: "2.0"
info:
  version: "0.1.0"
  title: "Pandas to Production"

host: "localhost"

basePath: "/api"

schemes:
  - "http"

paths:
  /pages/:
    get:
      tags:
        - "pages"
      operationId: "listPages"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Page"
    post:
      tags:
        - "pages"
      operationId: "createPage"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/PageInput"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Page"

  /pages/{pageId}:
    get:
      tags:
        - "pages"
      operationId: "getPage"
      parameters:
        - name: "pageId"
          in: "path"
          description: "Page ID"
          required: true
          type: "string"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Page"
    put:
      tags:
        - "pages"
      operationId: "createPage"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/PageInput"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Page"
    delete:
      tags:
        - "pages"
      operationId: "deletePage"
      parameters:
        - name: "pageId"
          in: "path"
          description: "Page ID"
          required: true
          type: "string"
      responses:
        204:
          description: ""

  /dataframes/:
    get:
      tags:
        - "dataframes"
      operationId: "listDataframes"
      responses:
        200:
          description: ""
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Dataframe"
    post:
      tags:
        - "dataframes"
      operationId: "createDataframe"
      consumes:
          - multipart/form-data  # and/or application/x-www-form-urlencoded
      parameters:
          - name: file
            in: formData
            description: The uploaded file data
            required: true
            type: file
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Dataframe"

  /dataframes/{dataframeId}:
    get:
      tags:
        - "dataframes"
      operationId: "getDataframe"
      parameters:
        - name: "dataframeId"
          in: "path"
          description: "Dataframe ID"
          required: true
          type: "string"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Dataframe"
    put:
      tags:
        - "dataframes"
      operationId: "updateDataframe"
      consumes:
          - multipart/form-data  # and/or application/x-www-form-urlencoded
      parameters:
          - name: "dataframeId"
            in: "path"
            description: "Dataframe ID"
            required: true
            type: "string"
          - name: file
            in: formData
            description: The uploaded file data
            required: true
            type: file
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/Dataframe"
    delete:
      tags:
        - "dataframes"
      operationId: "deleteDataframe"
      parameters:
        - name: "dataframeId"
          in: "path"
          description: "Dataframe ID"
          required: true
          type: "string"
      responses:
        204:
          description: ""

definitions:
  Page:
    type: "object"
    properties:
      id:
        type: "string"
      title:
        type: "string"
        example: "Weekly Report"
      content:
        type: "object" # TBD
      dataframe_id:
        type: "string"

  PageInput:
    type: "object"
    properties:
      title:
        type: "string"
        example: "Weekly Report"
      content:
        type: "string"
      dataframe_id:
        type: "string"

  Dataframe:
    type: "object"
    properties:
      id:
        type: "string"
      digest:
        type: "string"
      url:
        type: "string"
